// react/src/components/List.js
import React, { useState, useCallback } from "react";
import { Link } from "react-router-dom";
import "./List.css";
import axios from "axios";

function List() {
  const [term, setTerm] = useState('');
  const [books, setBooks] = useState([]);
  const [empty, setEmpty] = useState(true);

  const useAsyncHook = useCallback(async() => {
    const { data } = await axios.get( `https://www.googleapis.com/books/v1/volumes?q=${term}`);
    setBooks( data.items.map(book => ({ id: book.id, ...book.volumeInfo })) );
    setEmpty(false);
  })

  return (
    <div className="container">
      <input type="text" onChange={e => setTerm(e.target.value)} />
      <button onClick={useAsyncHook}>Search</button>
      <section className="cards-container">
      { empty === true ? 
        (<p>There's no item to show</p>)
        : (
          books.map(book => {
            return (
              <Link to={"/details/" + book.id} key={book.id} className="card">
                 <h4>{ book.title }</h4>
                 <img src={book.imageLinks ? book.imageLinks.thumbnail : ''} />
              </Link>
            );
          })
          )
        }
      </section>
    </div>
  )
}


export default List;

// angular/src/app/list/list.component.ts
import { Component, OnInit } from '@angular/core';
import httpClient from 'axios';

@Component({
  selector: 'app-list',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.css']
})
export class ListComponent implements OnInit {
  books = [];
  empty = true;
  term = '';

  constructor() { }

  ngOnInit() {
  }

  async search() {
    const { data } = await httpClient.get( `https://www.googleapis.com/books/v1/volumes?q=${this.term}`);
    this.books = data.items.map(book => ({ id: book.id, ...book.volumeInfo }));
    this.empty = false;
  }

}

<div class="container">
  <input type="text" [(ngModel)]="term" />
  <button (click)="search()">Search</button>
  <section class="cards-container">
    <div *ngIf="empty === true">
      There's no item to show
    </div>
    <div [routerLink]="['/details', book.id]" class="card" #elseBlock *ngFor="let book of books">
      <h4>{{ book.title }}</h4>
      <img src="{{ book.imageLinks.thumbnail }}" />
    </div>
  </section>
</div>
