// vue/src/components/Details.vue
<template>
  <section>
    <button @click="goBack">Go Back</button>
    <h2>{{book.title}}</h2>
    <p>{{book.authors.join(', ')}}</p>
    <img :src="book.imageLinks.thumbnail" alt />
    <p v-html="book.description"></p>
  </section>
</template>

<script>
import httpClient from "axios";

export default {
  name: "detail",
  data() {
    return {
      id: this.$route.params.id,
      book: {
        authors: [],
        imageLinks: {}
      }
    };
  },
  async created() {
    const { data } = await httpClient.get(
      `https://www.googleapis.com/books/v1/volumes/${this.id}`
    );
    this.book = { ...data.volumeInfo };
  },
  methods: {
    goBack() {
      window.history.length > 1 ? this.$router.go(-1) : this.$router.push("/");
    }
  }
};
</script>

<style scoped>
img {
  max-width: 120px;
}
</style>

// react/src/components/Details.js
import React, { useState, useEffect } from "react";
import { useParams, withRouter } from "react-router-dom";
import httpClient from "axios";

function Details({history}) {
  let { id } = useParams();
  const [book, setBook] = useState({ 
    authors: [],
    imageLinks: {}
  });

  function goBack() {
    history.goBack();
  }

  useEffect(() => {
    const getDataAsync = async () => {
      const { data } = await httpClient.get(`https://www.googleapis.com/books/v1/volumes/${id}`);
      setBook({ ...data.volumeInfo });
    };

    getDataAsync();
  });

  return (
    <section>
      <button onClick={goBack}>Go Back</button>
      <h2>{book.title}</h2>
      <p>{book.authors.join(", ")}</p>
      <img src={book.imageLinks.thumbnail} alt="alt" />
      <p dangerouslySetInnerHTML={{
         __html: book.description
      }}>
      </p>
    </section>
  );
}

export default withRouter(Details);
